# Generated by Django 3.0.11 on 2020-12-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='g',
            field=models.CharField(blank=True, max_length=67, null=True),
        ),
    ]
