# Generated by Django 3.0.11 on 2020-12-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201224_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='request_status',
            field=models.CharField(choices=[('NR', 'No request'), ('SENT', 'Request Sent'), ('DONE', 'Accepted Request'), ('BLOCK', 'blocked')], default='NR', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank='', default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, through='accounts.Friends', to='accounts.User'),
        ),
    ]
