# Generated by Django 3.0.11 on 2020-12-28 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20201228_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buddies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(blank=True, choices=[('SENT', 'Request Sent'), ('DONE', 'Accepted Request'), ('BLOCK', 'blocked')], max_length=30)),
                ('hand_shaked_on', models.DateTimeField(blank=True, null=True)),
                ('requested_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_from', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('requested_from', 'requested_to')},
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.AddField(
            model_name='user',
            name='buddies',
            field=models.ManyToManyField(blank=True, through='accounts.Buddies', to='accounts.User'),
        ),
    ]
