# Generated by Django 3.0.11 on 2020-12-28 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20201228_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buddies',
            new_name='Buddy',
        ),
    ]
