# Generated by Django 3.0.11 on 2020-12-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201230_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='', null=True, upload_to='profilepics'),
        ),
    ]
